### ISSUE TITLE
Picker Model (Basic) is incorrectly used.

### ISSUE THREAD

**Issue by vivekd005** [miyushan/mui-daterange-picker-plus#16]
The **Picker Model (Basic)** under the **Usage with Examples** section has syntax errors that cannot be used directly.

**Issue:-** useState Syntax is incorrect for **anchorEl**, **dateRangeOnChange** and **dateRangeOnSubmit**.

![image](https://github.com/user-attachments/assets/7b180d02-5fd6-4f74-95d2-f184408a5257)

**Fix*:-* replace these lines with the following lines and the Usage will work as expected.
`const [anchorEl, setAnchorEl] = useState<HTMLButtonElement | null>(null);`
`const [dateRangeOnChange, setDateRangeOnChange] = useState<DateRange>({});`
`const [dateRangeOnSubmit, setDateRangeOnSubmit] = useState<DateRange>({});`

**Comment by miyushan** [comment]
Hi @vivekd005, Readme was formatted improperly when I save it. Thank you very much for informing this issue.
Just now I released v1.0.8 by fixing this. Thanks.
